### ISSUE TITLE
Completion for struct type fields

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#1162]
```go
func main() {    
    WaitGroup{<caret>}
}

type WaitGroup struct {
    counter int32
    waiters int32
    sema    *uint32
}
```

**Comment by dlsniper** [comment]
Since I'm not sure how hard this one is to implement, may I suggest moving the target to 1.next in favor of solving other issues first?

**Comment by sclasen** [comment]
fwiw this worked in 0.9 and is among the most valuable features (to me personally at least) of the plugin.

**Comment by JoeBruner** [comment]
You know, I thought I was going crazy.   I swore that init'ing structs used to autocomplete fields but it hasn't for a bit.  I thought it was because the plugin was being buggy (sometimes it takes sooo long for the plugin to catch up to my typing that it seems like it's not working when it really is).  This definitely is a very useful feature.

**Comment by sclasen** [comment]
@ignatov is this in an alpha build yet?  I am not seeing it work, despite updating as soon as new alphas are available

**Comment by dlsniper** [comment]
@sclasen it is indeed in the alphas since a couple of weeks. Can you please open a new issue with a way to reproduce this? For me the feature works since it was commited. Thank you.
