### ISSUE TITLE
[1.0.0] can't detected import module from GOPATH

### ISSUE THREAD

**Issue by antonikonovalov** [go-lang-plugin-org/go-lang-idea-plugin#1192]
Always suggest import router, but router already import.
![2015-01-27 9 27 58](https://cloud.githubusercontent.com/assets/1614346/5914474/01dcaade-a607-11e4-91c5-7a9ea069b0d8.png)

may be with go1.4 not trouble

**Comment by dlsniper** [comment]
Hi. 

1.0.0,as the name of the branch suggests, is alpha state. Also, the issue is a side effect, and duplicate, of the issue described here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1163

Thanks

**Comment by zolotov** [comment]
@antonikonovalov It doesn't work when you run the application from IDEA, right?

What happens when you're running it in the real shell?
```
/usr/local/go/bin/go run /Users/antoniko/go/src/src-tms.als.local/go/chat-manager/server/main.go
```
What is the value of $GOROOT variable in your shell? What shell are you using? What OS are you using? IDE? IDE version? Go plugin version? Also screenshot of 'Settings | Languages & Frameworks | Go Libraries' could be useful. Thanks.

**Comment by dlsniper** [comment]
I think this was fixed along with the rework for go packages support @zolotov did a few days ago. @antonikonovalov can you please check alpha#11 release? Thank you.

**Comment by antonikonovalov** [comment]
I am used alpha#11 14.0.3. Now it's ok.
