### ISSUE TITLE
[1.0] Ide add package url suffix intead package name in autocomplete

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1304]
```go
package main

import "github.com/op/go-logging"

func main() {
	logging<ctrn+space, enter> // go-logging.GetLevel()
}
```

expects:
```go
logging.GetLevel() // as it shown in autocomplete popup
```

happened:
```go
go-logging.GetLevel()
```

plugin version: 1ac99ac032eafa63c936b747f34b815f01d2f34a

**Comment by dlsniper** [comment]
Cab you please provide an example of what expect and what's happening as well? Thank you.

**Comment by linniksa** [comment]
done. In popup i see right string, but after press enter it insert wrong code

**Comment by zolotov** [comment]
Guys I really need your help with imports, I completely can't understand the rules :)

So, the completion problem: completion sees that the package with GetLevel() function had already imported and inserts "local name" of this package. Because import statement doesn't contains alias we're following the rule "Go's convention is that the package name is the last element of the import path: the package imported as "crypto/rot13" should be named rot13." which I found [here](http://golang.org/doc/code.html#PackageNames). @linniksa, @dlsniper do you know why this rule doesn't work in this case and where I can find "a new rule"? 

Actually I can easily fix it for completion but we have similar problems in resolving, importing, caching and run configurations.

Btw, the last one is quite interesting, maybe you'll be able to help with it too. 
Let's we have a project "go-logging" with single file 'logger_test.go' with following content:

```package logging```

Assume I want to run go test for whole package. Well, I know that I shouldn't trust to directory's name, so I look at package statement in logget_test.go and run go test with 'github.com/op/logging' argument. And it doesn't work (package not found in GOPATH)! For some reason go-test accepts exactly directory name as a package.

**Comment by linniksa** [comment]
As mentioned in go blog post http://blog.golang.org/organizing-go-code#TOC_3.
> The last element of the import path is typically the same as the package name. For instance, the import path "net/http" contains package http. **This is not a requirement** - you can make them different if you like - but you should follow the convention for predictability's sake: a user might be surprised that import "foo/bar" introduces the identifier quux into the package name space.

**Comment by linniksa** [comment]
По поводу тестов я всегда думал что он принимает именно папку (ну или import path), например:

    go test .
    go test ./../../src/test-my/

**Comment by zolotov** [comment]
Упячка какая-то...

Ok then. Thank you. I've fixed completion issue and thanks to your explanation found yet another related bug in unused import inspection (https://www.dropbox.com/s/j4krs2myhhfyxri/Screenshot%202015-02-13%2021.07.46.png?dl=0).

**Comment by linniksa** [comment]
As i can understand the tests added by you - dirName package cannot be used in go because go not allow mix package names inside dirrectory

про Упячку не понял

**Comment by zolotov** [comment]
> go not allow mix package names inside dirrectory

Reference says it depends on compiler implementation, not sure if we need to support compilers that allows to do it

**Comment by zolotov** [comment]
Anyway, please try this build with completion fix: https://www.dropbox.com/s/pr1s9l9luii4tih/Go.76.zip?dl=0

**Comment by linniksa** [comment]
> Reference says it depends on compiler implementation
it for package import, but http://golang.org/doc/code.html#PackageNames
> All files in a package **must use the same name**.


test cases:


```go
package main

import (
	_ "github.com/op/go-logging"
)

func main() {
	logger<ctrl+space, enter> // got _.GetLevel() but should not be autocompleted
}
```

```go

package main

import (
	"./name"
)

func main() {
	name.AA() // after press enter it add "name" import instead use exists "./name"
}
```

**Comment by zolotov** [comment]
Didn't understand the first case, why it had shouldn't?
The second case is great, thanks

**Comment by linniksa** [comment]
because package import as unnamed and could't be used directly

**Comment by zolotov** [comment]
Got it, thanks.

**Comment by zolotov** [comment]
Fixed autoimport issues that were mentioned here
