### ISSUE TITLE
How to prevent automatic import block folding?

### ISSUE THREAD

**Issue by kalopsia** [go-lang-plugin-org/go-lang-idea-plugin#1314]
It's so annoying that editor automatically folds the import block. Can I somehow disable this behaviour?

```
package main

import ... // <--

func main() {
  //etc
}
```

**Comment by dlsniper** [comment]
I'm not sure this made it in to the ```alpha#58``` release but it will sure be fixed in the next release (it's in the code already).
To try out, go to ``` File | Settings | Editor | General | Code Folding ``` and untick the ```Imports``` option. I've forgot if this is per-project or global settings, sorry.

**Comment by kalopsia** [comment]
> To try out, go to File | Settings | Editor | General | Code Folding and untick the Imports option. 
I've already set it, but it doesn't make sense. Ok, got it. Thank you. So this behaviour will depend on the option above?

**Comment by dlsniper** [comment]
Yes. If it's not working it the release you have, please wait for the next one.
The plugin follows the options provided by IDEA for all the languages it has in order to be consistent and familiar with the users of the platform but I guess it's a very good case to add to the documentation.
Thank you.
