### ISSUE TITLE
[1.0]Can't select Go Library

### ISSUE THREAD

**Issue by alextc001** [go-lang-plugin-org/go-lang-idea-plugin#1317]
When i trying to select go libraries there is only loading message. I'm using 1.0.0.alpha#58 version.
![screen shot 2015-02-16 at 12 46 51](https://cloud.githubusercontent.com/assets/7407097/6210587/d9cfa1e4-b5d9-11e4-9c0f-997cc4ffa90c.png)

**Comment by dlsniper** [comment]
Hi @alextc001,

 How did you installed the plugin?
Since you are on Mac (as far as I can tell), can you please have a look at this section from the readme: _Note for **Mac OS X** users: you need to download the entire zip file, not a several jars (see [Apple discussion forum](https://discussions.apple.com/thread/1483114))_
Also which IDE / version are you using?
As a final note, there's a new alpha build (I'm not sure it's going to help, but it's newer nonetheless).
Thanks.

**Comment by alextc001** [comment]
Hello again,

Just updated to alpha#92 and now it works. Before i tried different versions of 1.0 and has the same problem. Thanks
