### ISSUE TITLE
[feature] Add ability to execute scratch files

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1544]
IntelliJ has the ability to do scratch files.  This sort of mimics the functionality of https://play.golang.org/ , however the go playground is limited in that you can't test against 3rd party libs.  The formatting and such works for Go files in IntelliJ, however, there is no way (that I can tell) to execute the file which is sort of limiting.   It is possible to execute scratch files for specific languages, and I don't see why Go couldn't be one of them

**Comment by dlsniper** [comment]
I've labeled this as 'next' as I'm not sure how hard it is to implement. If there's a place where I could have a look at something similar, I'd like to give it a try. Thank you.

**Comment by JoeBruner** [comment]
Apparently, according to http://blog.jetbrains.com/idea/2014/09/intellij-idea-14-eap-138-2210-brings-scratch-files-and-better-mercurial-integration/
@ignatov might already know about this issue and be working on it??

**Comment by dlsniper** [comment]
I'm not sure on what Sergey works on but that's why I've left the message here :) If he can point me in the right direction, I can have a try to do this (or anyone else for that matter, since the plugin is open-source).

But again, I don't know how hard it is to do / if it's a priority for the plugin to have this right now. Currently, one can simply create a new file, right click on it and select 'Run' then delete it when it's done and all the plugin features would be there :)

**Comment by ignatov** [comment]
At the moment scratches don't have extensions. And the `go run` command can't run them. 
Also see corresponding change https://github.com/golang/go/commit/ed936a3f22bcc8165390545471633141088eca26#diff-625aa2f64551b1e6337ca53cacf06be5R34

As a workaround you can add an extension manually, but it's not really convenient. Use rename refactoring **Shift+F6** or open the file in Scratches view **Alt + F1/Scratches**:
![screenshot 2015-04-11 00 28 01](https://cloud.githubusercontent.com/assets/426890/7097789/aa82d8b6-dfe1-11e4-9710-324c259af650.png)
