### ISSUE TITLE
Can not resolve directory '_workspace'  when using godep

### ISSUE THREAD

**Issue by sebcante** [go-lang-plugin-org/go-lang-idea-plugin#1584]
Hi, 

First, thanks for this amazing plugin, it is very useful!

I have one question, i migrated one of my go project to godep, the imports now refer to the Godeps/_workspace directory but for some reasons the plugin does seem to exclude *_workspace* directory. Is there a way to remove this exclusion or is there any workarround ? The impact is the import line become red and the autocompletion stopped working. 
``` 
import (	
	"myproject/Godeps/_workspace/src/github.com/bitly/go-nsq"
	"myproject/Godeps/_workspace/src/github.com/twinj/uuid"	
)
```

Environement plugin 0.9.291

thanks

-seb

**Comment by dlsniper** [comment]
This is intended as the ```go build``` command ignores anything starting with ``` _ ```, ``` . ``` or named ```testdata```. What's the use-case you have with godep? How do you structure your projects? Do you have multiple projects that don't obey the GOPATH rules?

**Comment by dlsniper** [comment]
For further reference: https://groups.google.com/forum/#!msg/golang-nuts/WS39uEWUA-0/A4WpJ1fLA_gJ and https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1490

**Comment by dlsniper** [comment]
More details on this.
There's three ways of using godep https://github.com/tools/godep 

One of them is to use ```godep restore``` which restores the packages from ```Godeps/_workspace``` to a GOPATH setup.
For this, we shouldn't be concerned with anything.

The second use case is prepending it to the go tools such as ```godep go env``` in which case the GOPATH will look like this:
```
GOPATH="/home/florinp/golang/src/github.com/tapglue/backend/Godeps/_workspace:/home/florinp/golang"
```
(original)
```
GOPATH="/home/florinp/golang"
```

As such, if people are using ```godep go tool``` approach, the solution would be to add the ```Godeps/_workspace``` to the ```Go Libraries``` under the ```Project Libraries``` section.

The last use case is when people rewrite their imports ```godep save -r``` which apparently might cause issues. For that I have nothing yet, sorry.

**Comment by sebcante** [comment]
thanks @dlsniper for the quick response and the clarification.

i use the last use case you mentioned,  godep with path rewriting `godep save -r`

the typical import statements instead of having:
`import ("github.com/bitly/go-nsq")`
 gets rewritten by `godep save -r`
`import ("bitbucket.org/mycompany/myproject/Godeps/_workspace/src/github.com/bitly/go-nsq")`

The benefit of godep path rewritting is it gives me a full self contained repo

**Comment by lindroth** [comment]
I have the same problem since 0.9.291. We also use paths like 
import ("github.com/mycompany/myproject/Godeps/_workspace/src/github.com/bitly/go-nsq")
Which does not work anymore. 

Adding Godeps/_workspace to the Go Libraries under the Project Libraries section does not solve it. As this would only fix imports of  ("github.com/bitly/go-nsq") right?

Anyhow, sadness. And it would be nice if this could be resolved in some way, as this is how godeps works.

We also choose this kind of usage of godeps because we get a self contained repo.

**Comment by dlsniper** [comment]
@lindroth and @sebcante can you please what's the behavior of the go tools in the following scenario:

- package demopack is in $GOPATH/src/test/_demo/demopack
- package demopack is in $GOPATH/src/test/demo/_demopack

And you include the package in a file from $GOPATH/src/test/main.go with this:
- ```import "test/_demo/demopack"
- ```import "test/demo/_demopack"

Once this behavior is established we can change the plugin to suite the go tool.

**Comment by jgroeneveld** [comment]
a package in a folder named _.. is not buildable

**Comment by gabrielf** [comment]
I'm new to go so maybe I'm not doing it right but here is a minimal project that uses both kinds of paths and it works with `go run` and `go build` but IntelliJ won't index the code in any of the _* directories.

https://github.com/gabrielf/go-underscore-sandbox

**Comment by jgroeneveld** [comment]
@gabrielf you are right, by convention I named my file _demopack/_demopack.go which will get ignored because of the underscore in the file, not the package name. 

the go documentation does not disallow underscores in package names but they are state that they should only contain lowercase letters and numbers. so the underscore package name is actually fine although not fitting the conventions.

**Comment by gabrielf** [comment]
So is this merely a matter of changing a pattern in the plugin so that packages beginning with underscore are accepted?

It seems reasonable to accept those given that they actually work with `go build` and `go run` plus that this is the way `godeps` work when vendoring dependencies. I've created a minimal project using `godeps` with vendoring here: https://github.com/gabrielf/go-godep-sandbox

**Comment by zolotov** [comment]
Exclusions are reverted for files in project (not in libraries)

**Comment by lindroth** [comment]
Thanks, that was quick. This is a really great plugin btw. Thanks for all the work!!!!!!!!11one

**Comment by zolotov** [comment]
@lindroth thanks. Does 0.9.300 work for you?

**Comment by sebcante** [comment]
@zolotov  i confirm 0.9.300 works for me with godeps path rewriting thanks a lot!!

**Comment by zolotov** [comment]
@sebcante cool, thanks for feedback

**Comment by gabrielf** [comment]
That was quick, nice! :+1:

**Comment by lindroth** [comment]
Works great!
