### ISSUE TITLE
Not an expression as function parameter should be highlighted

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#1588]
```go
package main

func main() {
	_ := []string
	a := []string{}
	println(a)
	
	println([]string) // should be error
	println([]string{})
}
```

**Comment by sjamesr** [comment]
@zolotov in your example ` _ := []string` should be an error too (invalid syntax). For example:

```go
package main

func main() {
	[]string
}

prog.go:4: syntax error: unexpected semicolon or newline, expecting {
```

Right now the Go plugin parser accepts this syntax and yields the following PSI tree:

```
GO_FILE(0,43)
  PACKAGE_CLAUSE(0,12)
    PsiElement(package)('package')(0,7)
    PsiWhiteSpace(' ')(7,8)
    PsiElement(identifier)('main')(8,12)
  IMPORT_LIST(12,12)
    <empty list>
  PsiWhiteSpace('\n\n')(12,14)
  FUNCTION_DECLARATION(14,42)
    PsiElement(func)('func')(14,18)
    PsiWhiteSpace(' ')(18,19)
    PsiElement(identifier)('main')(19,23)
    SIGNATURE(23,25)
      PARAMETERS(23,25)
        PsiElement(()('(')(23,24)
        PsiElement())(')')(24,25)
    PsiWhiteSpace(' ')(25,26)
    BLOCK(26,42)
      PsiElement({)('{')(26,27)
      PsiWhiteSpace('\n')(27,28)
      PsiWhiteSpace('    ')(28,32)
      SIMPLE_STATEMENT(32,40)
        LEFT_HAND_EXPR_LIST(32,40)
          LITERAL_TYPE_EXPR(32,40)
            ARRAY_OR_SLICE_TYPE(32,40)
              PsiElement([)('[')(32,33)
              PsiElement(])(']')(33,34)
              TYPE(34,40)
                TYPE_REFERENCE_EXPRESSION(34,40)
                  PsiElement(identifier)('string')(34,40)
      PsiWhiteSpace('\n')(40,41)
      PsiElement(})('}')(41,42)
  PsiWhiteSpace('\n')(42,43)
```

I'm trying to compare go.bnf to the go.y grammar from the go source but perhaps you have an idea what's wrong.

**Comment by zolotov** [comment]
@sjamesr you're right, thanks.

> I'm trying to compare go.bnf to the go.y grammar from the go source but perhaps you have an idea what's wrong.

I don't have. Please let me know if you find something interesting.

**Comment by sjamesr** [comment]
I think the issue may be that our grammar has ExpressionList, whereas go.y has an ExpressionList and ExpressionOrTypeList. Our ExpressionList permits type references whereas the Go grammar requires ExpressionOrTypeList wherever type references are allowed.

We should also not allow a situation like:

```go
package main

func main() {
	string
}

prog.go:4: type string is not an expression
```

We will have to do this during some kind of inspection because there's no way for the parser to know that `string` is a type reference and not some other identifier.

Continuing to stare at grammars...

**Comment by zolotov** [comment]
> We will have to do this during some kind of inspection because there's no way for the parser to know that string is a type reference and not some other identifier.

GoAnnotator is a good place for this, it starts before the inspections and after parsing, so it knows about types and file's PSI

**Comment by dlsniper** [comment]
I know that the referencing PR says it partially addresses the issue but so far I haven't found anything from this issue that hasn't been addressed in the current master. I hope it's ok if I close it so that other issues can be opened when similar situations appear (it makes keeping track of what's already done easier). Please feel free to reopen this if you don't agree. Thanks.

**Comment by sjamesr** [comment]
Oh yes, thank you. I believe the current checks should catch errors like this.
