### ISSUE TITLE
Cannot download the Plugin

### ISSUE THREAD

**Issue by mvbaffa** [go-lang-plugin-org/go-lang-idea-plugin#1598]
Error: DNS_PROBE_FINISHED_NXDOMAIN

**Comment by dlsniper** [comment]
Can you please provide more details? I can't even try to suggest something because the are too many possibilities. 

What url? Where do you see the error? Which IDE name and version? What country? Do use a vpn/proxy? Is this something that happens for other JetBrains addresses like their website? Have you tried to do the request again a bit later? Which dns resolver are you using? Have you tried Google dns or opendns? Have you correctly pasted the URL from the readme into the IDE like described in the readme? 

Once I have some details maybe I'll be able to help you out.

**Comment by mvbaffa** [comment]
Hi,

I am trying to download directly from your site the URL is: http://packages.go-ide.com/goide-windows_386.zip. I am in Brazil and there is no proxy. I have tried many times. It is not working right now.

From Intellij (version 14.1.2) I could install the Plugin but it is version 0.9.15.3. I seemed to work OK but I could not configure the SDK. 

Go was downloaded from the official site for windows.

Can you help me ?

**Comment by dlsniper** [comment]
Hi, now that you've sent more info, sure I can :)

The package you are referring is not meant to be downloadable anymore, that's why @mtoader took it out.

Instead of installing the 0.9.15.3 from the plugin manager, please see the readme https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds in order to get you started with the latest releases of the plugin. The official release will be updated when this one is a bit more mature but we have lots of people reporting good stuff for it so don't be scared by the alpha / nightly labels :)

Please let me know if there are any issues or close the ticket if the issues are solved.

Thank you.

**Comment by mvbaffa** [comment]
Thanks

But I have just download the Go SDK from the official Site. When I try to configure the SDK in Intellij I point to the C:\Go Intellij gives me no error but It does no install de the SDK.

I use Intellij for some time I have installed Scala, Erlang e many other SDK, 

My Java SDK is 1.8 64 bit version could this br the problem ?

Thanks again

**Comment by dlsniper** [comment]
With which version of the plugin are you experiencing the problem? If it's one of the latest versions, 0.9.250+ then I guess we'd need bit more details, else, please remove the old version of the plugin and install it via the method described in the readme, https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

Thank you.

**Comment by mvbaffa** [comment]
It worked, Thanks

**Comment by dlsniper** [comment]
Perfect. Have fun developing with the plugin & Go and if you have any other problems with it (that don't yet have issues) or suggestions, feel free to help us improve the plugin.
