### ISSUE TITLE
`git` not found

### ISSUE THREAD

**Issue by akaspin** [go-lang-plugin-org/go-lang-idea-plugin#1614]
Git is installed
```
$ which git
/usr/local/bin/git
```
But when I try import any package - i get following:
```
/usr/local/Cellar/go/1.4.2/libexec/bin/go get github.com/nu7hatch/gouuid
go: missing Git command. See http://golang.org/s/gogetcmd
package github.com/nu7hatch/gouuid: exec: "git": executable file not found in $PATH
```
From terminal - all OK.

**Comment by dlsniper** [comment]
As I don't have a Mac I defer to @zolotov on this one. My guess is that you could try to launch from the terminal and see if it's fixed, but that's not really a fix

**Comment by akaspin** [comment]
@dlsniper All working well from terminal:
```
$ go get -u -v github.com/nu7hatch/gouuid
github.com/nu7hatch/gouuid (download)
```
But not from IDEA.

**Comment by dlsniper** [comment]
That's because the default way you launch an app from the UI of the OS vs terminal vs where you've set the path (on Linux you can use /etc/environment for example). I guess you can read more here: http://serverfault.com/questions/16355/how-to-set-global-path-on-os-x 

I've seen a few issues opened on YouTrack from others describing similar issue with ```/usr/local/bin``` missing or other differences between environment variables so I'm not sure how to tackle this. @zolotov / @ignatov any thoughts?

**Comment by akaspin** [comment]
@dlsniper But earlier everything worked fine. `/usr/local/bin` in $PATH in both `env` and `environment.plist`.

**Comment by dlsniper** [comment]
Uhm... ok, which version of the plugin do you have? There was a small change to how the PATH is set in the plugin so that may have interfered with something in there. Unfortunately I don't have a Mac so I can't test (and I don't use go get from the plugin for example).

**Comment by akaspin** [comment]
@dlsniper `0.9.309`

**Comment by bronze1man** [comment]
looks like https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1586#issuecomment-97647319

**Comment by zolotov** [comment]
@akaspin please try >= 0.9.312

**Comment by akaspin** [comment]
All works. Thanks.
