### ISSUE TITLE
Need help setting CGO_CFLAGS in IDE

### ISSUE THREAD

**Issue by asogor** [go-lang-plugin-org/go-lang-idea-plugin#1684]
I have a  project uses: https://github.com/jmhodges/levigo
It needs:
    CGO_CFLAGS="-I/path/to/leveldb/include" CGO_LDFLAGS="-L/path/to/leveldb/lib" go get 

How can I set it in the IDE, which menu item? I can do it in command line but I wonder if there is an elegant way?

Aron

**Comment by zolotov** [comment]
It's impossible to set these variables for `go get` that is invoked from IDE. Why do you need this btw?

For building/running you can set these flags in particular Run Configuration | Environment variables field

**Comment by dlsniper** [comment]
Hi, as far as I can understand you'd want to add those to the ```go get``` part. For that you can't set custom params / env variables.

However, if you build your app using that library, your run configuration and add the following params to the go tool parameters section:

```
-a -ccflags "-I/path/to/leveldb/include" -ldflags ''-L/path/to/leveldb/lib"
```

Note, the ``` -a ``` is there to force Go to rebuild the packages thus allowing you to build the app with the correct settings in this case.

**Comment by dlsniper** [comment]
> Why do you need this btw?

For that particular library it seems you should send the values for where the LevelDB stuff is so that the package is properly built by Go. Given the fact that Go won't rebuild the package unless it's changed, running ```go get``` without it might not configure it properly (and unless you run with ```-a``` it will remain like that until a new version is pulled).

@asogor please correct me if I'm wrong.

**Comment by asogor** [comment]
@dlsniper you are right building it outside worked.
