### ISSUE TITLE
Don`t redirect output to /dev/null while debugging

### ISSUE THREAD

**Issue by mkabischev** [go-lang-plugin-org/go-lang-idea-plugin#1699]
Hi.

While debugging commands runs like
```
Starting program: /path/to/main > /dev/null
```
so "Console" tab is empty. It isn`t useful. Was there any reason to do so?

**Comment by dlsniper** [comment]
According to this: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/debugger/ideagdb/run/GdbRunner.java#L96 it's a left-over.

I know from the previous implementation of the GDB support that it's a pain to have it done as well since then the parser will get complicated due to GDBs poor API so I guess that's the reason as well.

**Comment by dlsniper** [comment]
This was applicable when GDB was used as a debugging backend, however we have now delve which doesn't have the same issue. Closing this for now.
