### ISSUE TITLE
The selected directory is not a valid home for Go Sdk

### ISSUE THREAD

**Issue by jritchie** [go-lang-plugin-org/go-lang-idea-plugin#173]
Windows 8
IntelliJIDEA Ultimate 12
Plugin Version 0.9.12

Upon choosing the Go 1.0.3 SDK located at C:\Go an error dialog is displayed with the following message:

The selected directory is not a valid home for Go Sdk.

**Comment by kortemy** [comment]
I have this behavior with go1.5beta1, I upgrade after I installed fresh OS few days ago.

kortemy@kortemy-vaio:~$ go version
go version go1.5beta1 linux/amd64

kortemy@kortemy-vaio:~$ go env
GOARCH="amd64"
GOBIN="/home/kortemy/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kortemy"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Installed via download, not apt (obviousuly, its 1.5).

IDEA version: idea-IC-141.1532.4

Plugin version: 0.9.371 (latest from alpha repo in time of writing).

OS: elementaryOS freya (0.3) linux kernel 3.16.

Note: 1.4 was working perfectly on elementaryOS luna (0.2), both IC and WebStorm are working normally, and go1.5 works as expected from terminal.

My best guess is that its due to Golang version 1.5. In any case, it needs to be supported.

**Comment by dlsniper** [comment]
@kortemy thanks for the complete info (I wish all reports were like this). The problem has been fixed in the nightly channel, please try that one and it should work. If not let us know.

**Comment by kortemy** [comment]
@dlsniper Wow, that was quick. :) Works like a charm now, thanks!

**Comment by YeTianZhou** [comment]
update ideaIU to the latest version,and all is run

**Comment by yanggangying** [comment]
换一个版本就好了

**Comment by yanggangying** [comment]
change another  version   for example  1.0.2
