### ISSUE TITLE
Add inspection for doing a defer in an infinite loop

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1776]
There should be an inspection for the following case:

```go
for {
    src, err := os.Open(srcName)
    defer src.Close() // this should be marked with a warning
}
```

```go
for {
    src, err := os.Open(srcName)
    if err != nil {
       break
    }
    defer src.Close() // this should be marked with a weak warning because there's a break in the for loop
}
```

The problem:
- os.Open requires the resource to be closed via ```Close()``` method
- if the defer statement is placed in an infinite for loop ```for { ... } ``` then the deferred statement will never be called thus resulting in resources which will be leaking / can't be properly closed / gc-ed

To be more clear, the defer inside the loop is the problem, the object might not have a ```Close()``` method, it might be something totally different.

**Comment by ignatov** [comment]
@dlsniper Please provide a link for the further reading or add a more detailed description.

**Comment by dlsniper** [comment]
Hi, I've updated the description to be a bit more clear, let me know if it's better or I should add some other examples.

**Comment by linniksa** [comment]
I think all deffers call to local variables of loop can be marked as warning

**Comment by packrat386** [comment]
http://play.golang.org/p/MORqjYbI-J

Defer inside an infinite loop can be called by a panic. No need to warn for it.

**Comment by dlsniper** [comment]
> if always loop one time - loop is not needed

That would imply the IDE understands the number of iterations that the loop has, which is a very rare case (unless the numbers can be inferred, I don't see how the IDE should detect this).

> Defer inside an infinite loop can be called by a panic. No need to warn for it.

Even if defer is called when the code panics, resource starvation is just one of the issues that can appear. Think of use-cases where the code shouldn't panic or shouldn't be stopped at all, if the application dies because of too many resources being allocated but not freed then that's a huge problem. Relying on panics to free resources is a bad practice / code smell imo (and I think people on golang-nuts, the place where I've seen this being discussed as well a few times would agree with it).

And finally, inspections can be turned on or off but I think this one should be considered to be on by default in my opinion.

**Comment by fgrosse** [comment]
I came here because I got a bit worried by the warning. In my understanding it is perfectly fine to stack defers in a loop. There are multiple popular examples that do just that:

- [A Tour of Go - Stacking defers][1]
- [Effective Go - Defer][2] 
- [The Go Blog - Defer, Panic and Recover][3]

Also consider [this playground example][4]

Defering in a loop really only becomes a problem if the loop never ends. More generally `defer` in *any* function is a problem if that function blocks infinitely.

If you decide to keep the warning I suggest you should add more information so this doesnt discourage defer in a loop in general. Alternatively I think this warning can just be removed because it is very confusing to the user and will more often warn about functionally correct code than not.

[1]: https://tour.golang.org/flowcontrol/13
[2]: https://golang.org/doc/effective_go.html#defer
[3]: https://blog.golang.org/defer-panic-and-recover
[4]: https://play.golang.org/p/TMwXX-G60j

**Comment by dlsniper** [comment]
I think it we could change this to do a check if the loop is unbounded or not.
If you can think of a better description please feel free to send it.
And while yes, there are legitimate places where this can be used, but I'd say that overall there are more cases where this shouldn't be used than it should. For example: https://play.golang.org/p/tGiHFHKzQH
Also, it's a weak warning, not a warning, so it's meant to flag that there's a possible warning but not necessarily something is awfully wrong.

@zolotov / @ignatov what do you guys think? I can make some adjustments to it.

**Comment by zolotov** [comment]
> If you decide to keep the warning I suggest you should add more information so this doesn't discourage defer in a loop in general.

It makes sense. You can contribute more appropriate description (or send it to @dlsniper), the description is located at https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/resources/inspectionDescriptions/GoDeferInLoop.html

**Comment by fgrosse** [comment]
Sorry for the late reply, If I can come up with a better description I will submit a pull request. 

Based on the discussion in this issue I would include the following information:
- defer may never happen if the loop does not exit
- defer may be unreachable due to early returns or breaks (not sure this belongs here)

@dlsniper 
I don't really see the problem in that playground example. In fact this mostly seems to be a copy of the example from [the official Tour of Go][1]. Is this about the LIFO semnatics or stacked `defer` calls? This is just the way `defer` works and I am confused that the user is warned about this. Also conceptionally this has nothing to do with the loop.

About the weak warning vs warning: in my experience people should not be encoruaged to ignore any warnings. The concept of weak warnings is really counter productive in that context. Maybe this could become something that turns up as "potential bug" when running the "Inspect Code" feature of  IDEA?

[1]: https://tour.golang.org/flowcontrol/13

**Comment by pjebs** [comment]
You can try my package https://github.com/rocketlaunchr/igo for this scenario.

Or alternatively use the `stack` subpackage to implement it.
