### ISSUE TITLE
colors & fonts settings clash

### ISSUE THREAD

**Issue by nhooyr** [go-lang-plugin-org/go-lang-idea-plugin#1778]
the package struct/interface colors clash with type specification and the plugin ends up using the type specification in the code (the package struct/interface colors are never used because type specification colors are used). also in the highlight sample privateField/func uses identifiers colors which isn't true. It would also be nice if the highlighting sample used all the colors, in every combination, if need be I can create this sample. This is all on the latest version nightly.

**Comment by aubble** [comment]
the first part is my mistake, the second part still stands though.

**Comment by aubble** [comment]
you guys should look the whole colouring thing over, there is another useless setting, type reference. I'm not sure what to use it for. I click on it and it shows as the type colour for method declarations except it doesn't actually do anything. The colour actually used for that is type specification.

**Comment by dlsniper** [comment]
@ignatov I'll have a look into this in the coming weekend.

**Comment by dlsniper** [comment]
@ignatov regarding the interface method setting right now this doesn't work as expected because we don't have a way to tell if the receiver type of the method implements an interface. The Go description of a "type implementing an interface" is that you you have all the methods with the same signatures declared in the interface attached to the receiver type. E.g.:

```go
package main

type Demo interface {
	Func1()
	func2() int
}
type demo interface {
	Func1()
}
type dem int
type de string

func (d dem) Func1() {}

func (d dem) func2() int {
	return int(d)
}

func (d de) Func1() {}
```

In this case ```dem``` implements both ```Demo``` and ```demo``` interfaces but ```de``` implements only ```demo``` interface (I hope it's clear enough).

**Comment by dlsniper** [comment]
The point of the message was to say that I'll try and implement this check but any pointers would be appreciated.

**Comment by dlsniper** [comment]
Actually it seems I don't know where to place a function that would check if a type implements an interface. My idea is to have something like this:
```
function TypeImplementsInterface(PsiElement goType, PsiElement goInterface) {
}
```
