### ISSUE TITLE
Continuous builds?

### ISSUE THREAD

**Issue by wrouesnel** [go-lang-plugin-org/go-lang-idea-plugin#1830]
This may already be possible, but its not clear from the documentation how: can you have the plugin continuously build a project and parse errors into idea so you can jump to them?

**Comment by dlsniper** [comment]
Hi, this feature is not supported by the plugin.

There's no need for it, theoretically, as the one purpose of the plugin is to show you errors before the compilation step. Also, it would be impractical to have something running on save events as due to the architecture of IntelliJ platform, the even can happen from multiple places. 

If you want to quickly run a project I suggest that you use the shortcut for the run option and make the run configuration as a single instance, that way all the resources (IDE tool windows) are shared between runs.

If you encounter situations where the ide doesn't show errors but it should, please open up separate issues so these can be addressed in the future. 

Thank you.

**Comment by dlsniper** [comment]
I've forgot to mention, when you will try to run the program and there's a compilation issues or a panic, the ide will try and provide links within the output for the files where the errors happen.

**Comment by ctd1500** [comment]
If it's enough, you can at least continuously run a test configuration upon code change, which can re-build your project. 
You can enable that after you run the test you want and then click the auto-test button, as shown highlighted red in the screenshot below.
![continuous build](http://i.imgur.com/x3tIf55.png)
