### ISSUE TITLE
Unexpected "Redeclared import error"

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#1858]
Import appears as redeclared.
strconv imported once and used in two places.
Bug didn't show up in 491 build.

![image](https://cloud.githubusercontent.com/assets/4350891/9830194/9eaaaea8-58d9-11e5-9e8d-6bdce78d75d3.png)
![image](https://cloud.githubusercontent.com/assets/4350891/9830240/c69dd62c-58db-11e5-84b3-084731bbc9bd.png)

![image](https://cloud.githubusercontent.com/assets/4350891/9830186/57521bcc-58d9-11e5-97f0-5d610b5435f2.png)
![image](https://cloud.githubusercontent.com/assets/4350891/9830191/6cc10536-58d9-11e5-9f9a-0c9b6f504588.png)

**Comment by dlsniper** [comment]
@vburenin do you have a code sample that can reproduce the bug? Thank you.

**Comment by sjamesr** [comment]
I can reproduce this problem at HEAD, I think the problem is that:

GoFile.getImportMap() will return an import map like

"runtime" -> "import runtime"
"main" -> "import runtime", "import strconv"

even though no explicit "import main" ever occurred. This is because GoFile
calls GoUtil.getAllPackagesInDirectory(dir, true) to resolve all packages
referred to by an import.

The redeclared input check I added in
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/e220fc0ecc79e3a7af836c0909db3b6b0f5ea067
will add a redeclared import warning if the package name has more than one
import spec in the import map.

I'm not sure what the correct solution is. :)

**Comment by sjamesr** [comment]
I think https://github.com/sjamesr/go-lang-idea-plugin/commit/1c92482379861453456fc542ce657c559fe5715e should fix it, I can't think of any other way that doesn't involve treating packages like "main" specially or understanding build tags.

**Comment by dlsniper** [comment]
I'm wondering if we should split this inspection into two different ones, regardless of duplicating the code. The reason is that it will make things easier to disable / enable. What do you guys think?

**Comment by zolotov** [comment]
@sjamesr Why do you think that `main` package should be ignored? What's special with it? Why for other cases `main` package shouldn't be ignored? What if I import some package that has files with `main` package only? Why this package is considered as unimportable? Should we handle this situation too?

In short, I definitely don't want to duplicate code and make any hasty solution just to fix some particular bug.

@dlsniper splitting is not the point, personally I don't care whether enabled by default inspections are splitted or not.

**Comment by sjamesr** [comment]
In the Go source distribution, you have situations like

```
src/runtime/mkduff.go -> package main, // build +ignore
src/runtime/trace.go -> package runtime, no build tag

src/strconv/makeisprint.go -> package main, // build +ignore
src/strconv/itoa.go -> package strconv
```

In your program, you do
```
import "runtime"
import "strconv" <--- redeclared import error
```

This is because `getImportMap` returns

```
main -> [runtime, strconv] <--- two imports with the same name, "redeclared import"
runtime -> [runtime]
strconv -> [strconv]
```

Is getImportMap doing the right thing?

**Comment by zolotov** [comment]
> Is getImportMap doing the right thing?

Not sure, maybe not. I think you've made a good catch with //build flags, looks like they should be processed in GoUtil#getAllPackagesInDirectory.

**Comment by sjamesr** [comment]
It seems like we might want to add `allowed` as a predicate to the condition in `getAllPackagesInDirectory`:

```java
if (file instanceof GoFile && allowed(file) && !directoryToIgnore(file.getName())) {
```
Right now, in order to determine whether a "C" import is made, `allowed` eventually calls `getImportMap` which again calls `getAllPackagesInDirectory`.

**Comment by sjamesr** [comment]
I uploaded a change for your consideration, but I'm not sure if it's correct. I changed `GoFile.hasCImportPath` to simply look for imports of the form `import "C"`, rather than seeing if any of the import paths resolve to a package named "C".

I'm not enough of a Go expert to know if this is correct.

**Comment by zolotov** [comment]
> I changed GoFile.hasCImportPath to simply look for imports of the form import "C", rather than seeing if any of the import paths resolve to a package named "C".

Looks like the approach you've implemented is correct, thanks.
