### ISSUE TITLE
No breakpoints in IntelliJ IDEA 14.1.4

### ISSUE THREAD

**Issue by mrz1836** [go-lang-plugin-org/go-lang-idea-plugin#1865]
IntelliJ Build# IC-141.1532

Just updated the Go plugin to version: 0.9.485

Running Windows 8.1

There are no breakpoints available in any of my Go files. I reverted the plugin and went back to the last stable release and the breakpoints work.

**Comment by dlsniper** [comment]
This is working as intended, assuming that the version you mention was 0.9.460. If that's incorrect the same explanation still applies.

The latest stable plugin version **is** 0.9.485. 

However the debugging engine behind it is now delve not gdb. Delve does not support yet Windows, as it's written in the documentation link provided in the release notes: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#debugging-a-go-project 
If you'd like to have this working, please contribute to delve, the link to the issue is this: https://github.com/derekparker/delve/issues/198 or wait until someone is able to do so.

Thank you for your understanding.
