### ISSUE TITLE
go library not find under debian

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1872]
my bash env:
```
mmc@mmc-debian:~$ cat ~/.bash_profile 
export PATH=~/python/python3/bin/:$PATH

export GOROOT=~/golang/go
export GOPATH=~/golang/3rdLibs:~/golang/myLibs:~/golang/myApps
export GOBIN=
export PATH=$PATH:$GOROOT/bin:${GOPATH//://bin:}/bin
```

i checked option 'run command as login shell' for bash

plugin could not automaticlly find my go lib path such as "~/golang/3rdLibs" ans "~/golang/myLibs"
i have add "src" directory under those paths, plugin cound not find yet.

plugin version 0.9.501

**Comment by dlsniper** [comment]
Hi,

Please add the following to the issue:
- plugin version
- IDE name and version.

Assuming you are using latest nightly / alpha here's how you can look into things further:
- the layout of the GOPATH should be respected by each directory:
 - `~/golang/3rdLibs` should be like this:
  - `~/golang/3rdLibs/bin`
  - `~/golang/3rdLibs/pkg`
  - `~/golang/3rdLibs/src` (which also contains the packages, e.g.   - `~/golang/3rdLibs/src/github.com/dlnsiper/u`
  - `~/golang/myLibs/bin`
  - `~/golang/myLibs/pkg`
  - `~/golang/myLibs/src` (which also contains the packages, e.g.   - `~/golang/myLibs/src/github.com/dlnsiper/new_u`
  - `~/golang/myApps/bin`
  - `~/golang/myApps/pkg`
  - `~/golang/myApps/src` (which also contains the packages, e.g.   - `~/golang/myApps/src/github.com/dlnsiper/new_u`

If that's the layout, then try to launch `idea.sh` from your bash prompt and see how things work. In my case this works quite ok (additionally I've manually changed idea.sh to be like this so that I don't have to launch the IDE from shell always:

```bash
export PATH='my-full-PATH-here'
export ANDROID_HOME='/home/florin/android-sdk-linux'
export GOPATH="/home/florin/golang:/home/florin/IdeaProjects"
```

However, this should not be a problem, if the paths are correct, you should just be able to add: `~/golang/3rdLibs` and `~/golang/myLibs` to the IDE by going to File -> Settings -> Languages & Frameworks -> Go -> Go Libraries -> Global Libraries (the green + corresponding to that section).

Additionally, GOROOT should not be set (unless you understand why you are setting it), so it might be safe to remove it from your environment.

**Comment by ziyouchutuwenwu** [comment]
as i forgot my debian notebook in company, so i reinstalled debian with virtualbox, here is my vm env.


i install the latested version of webstorm, install the nightly build version of golang plugin.

my ~/.bash_profile
```
export GOROOT=~/golang/go
export GOPATH=~/golang/3rdLibs:~/golang/myLibs:~/golang/myApps
export GOBIN=
export PATH=$PATH:$GOROOT/bin:${GOPATH//://bin:}/bin
```

i installed web framework such as beego(http://beego.me/quickstart)
```
go get github.com/astaxie/beego
go get github.com/beego/bee
```
the 3rdLibs now has three directories, the tree cmd output was much too long......

ide, webstorm linux version
http://download-cf.jetbrains.com/webstorm/WebStorm-10.0.4.tar.gz

```
if i start webstorm from bash, it seems webstorm can find go lib path,
if i start webstorm from mouse click, webstorm could not find the lib path.
```

btw, how should i set my env except setting /etc/environment ?
thank you very much

**Comment by dlsniper** [comment]
Ok, as I suspected it's not something we can fix from the plugin, it's just things work. 

There are two ways to fix this :
- edit idea.sh and add "export gopath...." to it
- use the settings I've mentioned earlier:
> add: ~/golang/3rdLibs and ~/golang/myLibs to the IDE by going to File -> Settings -> Languages & Frameworks -> Go -> Go Libraries -> Global Libraries (the green + corresponding to that section).
