### ISSUE TITLE
"No Such Process" and "process must be stopped in order to kill it" when debugging with delve

### ISSUE THREAD

**Issue by johnnadratowski** [go-lang-plugin-org/go-lang-idea-plugin#1917]
I was excited to try out the integrated delve debugger in the golang plugin, but hit some issues right away.

I noticed my breakpoints would have (x) over them when debugging.  When I hovered over them, it gives me a red error stating "no such process".

When I try to kill the process, it gives me an error "process must be stopped in order to kill it" and doesn't kill the underlying debugger process.

**Comment by dlsniper** [comment]
Hi @johnnadratowski thanks for reporting this.
Please include some more details such as:
- which plugin version do you have
- what operating system
- what IDE (and version)
- clear steps on how to replicate this and most of all, sample code on which we can apply the steps. Otherwise it's pretty hard to understand where the error happens or what actually happens there.

Thank you.

**Comment by johnnadratowski** [comment]
* uname -a output
    * Linux wilykit 4.2.3-1-ARCH #1 SMP PREEMPT Sat Oct 3 18:52:50 CEST 2015 x86_64 GNU/Linux
* IntellJ IDEA 14.1.5 build from 22nd of Sept
* go plugin version 0.9.545
* golang version 1.4

Steps:

* Setup my Go SDK and GOPATH.  
* Set breakpoint
* Try to run debugger

Noticed this behavior afterwards.

Console Output: 

/home/john/lib/go/bin/go build -o "/tmp/Build main.go and run0go" -gcflags "-N -l" github.com/Unified/platform
/home/john/.IdeaIC14/config/plugins/Go/lib/dlv/linux/dlv --listen=localhost:42379 --headless=true exec "/tmp/Build main.go and run0go" --
2015/10/13 15:11:53 Starting Server
process must be stopped in order to kill it


I've tried this with both a work project and an example single go file project.

**Comment by dlsniper** [comment]
Please try to rename the run configuration from `Build main.go and run` to something like `demo`.
I'm really not sure about which version of delve it's shipped with that particular release but I believe it's not updated to include the fix from delve to allow debugging of programs with spaces in their path / name.

If that doesn't solve it, please share some code to be able to try and reproduce the issue. Thank you.

**Comment by johnnadratowski** [comment]
Success! Wonderful! Thank you for the very quick response.

**Comment by dlsniper** [comment]
Happy to help. Please note that there might be some rough edges here and there, either on delve or on the plugin side so if you bump into something, the more detail we have the easier is to track down the issue. Enjoy coding ;)

**Comment by gtaylor** [comment]
I'm having this same issue and have tried the suggested rename fix:

uname -a output
Linux riggs 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
PyCharm 5.0.1
go plugin version 0.10.680
golang version 1.5.1

Pre-build:
![image](https://cloud.githubusercontent.com/assets/75556/11258624/82b8a374-8e0f-11e5-8448-2d7385e5aa75.png)

Post-build:
![image](https://cloud.githubusercontent.com/assets/75556/11258619/7b03d9dc-8e0f-11e5-9484-97b5b70b091a.png)

Also getting the ``process must be stopped in order to kill it`` message when I kill the session.

``ps aux | grep drone`` shows:
```bash
greg.ta+ 18770  0.0  0.0 127272 15548 ?        Sl   16:13   0:00 /tmp/drone0go
```
Doesn't seem to be the space issue.

**Comment by dlsniper** [comment]
@gtaylor can you please open a separate issue as this one has been solved and it was in fact related to spaces in the path? And please mention in the issue if there are any symlinks to your project, there seems to be an issue (still open)  with those as well. Thank you for otherwise a good issue report.

**Comment by gtaylor** [comment]
Done! Now with even more screenshots.

Thanks, @dlsniper
