### ISSUE TITLE
Plugin incompatible with builds 143.*

### ISSUE THREAD

**Issue by mmindenhall** [go-lang-plugin-org/go-lang-idea-plugin#1920]
The latest 15 EAP builds have changed the major build number (whatever that means at JetBrains) from 142 to 143.  This results in the following message when checking for updates:

`Plugin incompatible with the new build found: Go`

OS: Mac OS X 10.10.5
JDK version: 1.8.0_40
IDEA version: IDEA 15 EAP IU-142.5239 (trying to update to 143.249)
Plugin version: 0.9.460

**Comment by zolotov** [comment]
That's why README contains following lines:
```
Supported IDEs Pre-release builds can be installed on IntelliJ platform 141.1532 or greater and less than 141.9999.
```

We'll update since-update build numbers as soon as plugin became compatible.

**Comment by mmindenhall** [comment]
Thanks.  FYI, there's a mismatch between the README and the actual supported versions, as 0.9.460 supports 142.*.

```xml
<idea-plugin downloads="170938" size="1226998" date="1439846248000" url="">
   <name>Go</name>
   <id>ro.redeul.google.go</id>
   <description>Support for Go programming language. 
      <p>Alpha pre-release of the 1.0.0 version.</p> 
      <p>Doesn't contain all the functionality of the 0.9.x branch but has a completely reworked internals.
      It's faster than 0.9.x, refactoring works to some degree and has native support for gopath 
      packages.</p> Compatibility 
      <p>Plugin can be installed on IntelliJ platform 141.1532 or greater. It corresponds to IntelliJ IDEA 
      14.1.4, WebStorm 10.0.4, PhpStorm 9.0, RubyMine 7.1.3 and PyCharm 4.5.2</p></description>  
   <version>0.9.460</version>
   <vendor email="" url="https://github.com/go-lang-plugin-org"/>
   <download-url>../../plugin/download?updateId=20914</download-url>
   <idea-version min="n/a" max="n/a" since-build="141.1532" until-build="142.2147483647"/>
   <change-notes></change-notes>
   <rating>4.4</rating>
</idea-plugin>
```

**Comment by dlsniper** [comment]
Short verison:
@mmindenhall there is no mismatch there. Version 460 supported 142.xxx builds, newer versions since then do not. The statement is correct for version 460.


Long version:

The plugin supported builds until ` until-build="142.2147483647"` for releases before 485 as that was the release version for Android Studio. Because Android Studio and IntelliJ Platform have such different release numbers and when delve was released some APIs where needed that were changed in the the 142 branch the plugin was set to be usable only under the 141 branch of IntelliJ Platform.

Since IntelliJ IDEA 15 is not yet released as stable, the plugin does not yet support 142.somethingThatICantRecallNow or 143.somethingSomething or any other version that it's not mentioned in the main readme file.

What Zolotov mentioned above is still valid as well, when IDEA 15 will be released, the plugin will also be upgraded to support the latest and greatest. Until then, you are out of luck unfortunately. Hope this makes things clear now.

Cheers

**Comment by gesellix** [comment]
wouldn't it make sense to support a version range up to `149.1000` or so? In case the plugin doesn't work with a fresh EAP, it would be a chance to find issues (on the plugin or the IDEA side) and resolve them before a stable release.
I'd personally even prefer a special plugin build (nightly/eap/whatever) with a wide version range.

**Comment by ignatov** [comment]
Right now it's impossible to build the plugin against of IntelliJ 15 EAP. The issue will be fixed soon.

**Comment by gesellix** [comment]
@ignatov sounds great, thanks for the quick feedback!
