### ISSUE TITLE
Broken test file inspections

### ISSUE THREAD

**Issue by gmack** [go-lang-plugin-org/go-lang-idea-plugin#1926]
As of the latest update, inspections are broken for types in _test.go files.  None of my project settings have changed, not GOPATH or GOROOT.  They are both set as in the instructions.  In the previous version of the plugin, all inspections were working correctly, whether in regular code or in tests. 

Summary of behavior:
* In a given package, let's say you have a test_helpers.go file, containing:
package mypackage
...
type MyEmbeddedTestBase struct {
     baseField1 string
     baseField2 int
}

* Inside the same package, let's say you have a _test file with the following:
package mypackage
...
type MyTestSuite struct {
    MyEmbeddedTestBase 
    someField string // etc..
}

func (r *MyTestSuite) Funky() {
    r.baseField1  //  <--- inspections now believe this is an unresolved reference
}

* However, all code compiles ok, AND all tests compile and pass, including the test struct that the inspector believes has unresolved references. 

This is new mis-behavior, that only affects inspections, not compilation or testing.  And this only happens in _test files.  The test files in question share the same package name as the non-test files.

Is there a change in which the source paths or class paths have to be defined in the project setup?  

We are using godep as well, but as I mentioned, this was not an issue until the latest revision of the plugin.

**Comment by dlsniper** [comment]
Hi.

- which plugin version do you have?
- which instructions have you read about `GOROOT`? I don't remember to have one for the latest versions of the plugin (in fact for the versions released this whole year)
- can you share some sample code because from your description I can't replicate the issue on my machine using the latest nightly.

Cheers

**Comment by gmack** [comment]
Plugin version: 0.9.554
IntelliJ version: 14.1.5 build 141.2735  // <--- your instructions do say the support is for 14.1.4, though

Perhaps the GOROOT part is not needed anymore, but this is has not changed in the environment.

I'm guessing that the slightly new build of IntelliJ might have issues.  it's also not entirely clear how the "go library paths" in the project structure should actually work, but this is not an issue with 3rd party packages.

I'll work on a buildable sample for you.

**Comment by dlsniper** [comment]
Thanks for the update.

The readme says: ` Pre-release builds can be installed on IntelliJ platform 141.1532 or greater and less than 141.9999. ` Idea 14.1.5 is supported, and there shouldn't be any issues with it.

What configuration do you have in regards to the Go libraries? How does GOPATH looks like in your system and how do the Go libraries look like in your project? Where is your project path? That should shed some more light on the issue.

Thank you.

**Comment by gmack** [comment]
So I did the following:
* Opened RubyMine, which I also license.  And it also had your plugin.  No problems with inspections at all. 
* Installed IntelliJ EAP Version 15.  Oddly when going through the instructions to install the plugin, it picked out an earlier version, 0.9.250.  Imported a project, went through the process.  Also no problems and no inspection issues!

So, at this point, I'm going to close this issue, even through whatever was wrong with IJ 14 was never revealed.  I need to get to work, so since IJ 15 and RM both work, I'll use those, and leave 14 behind. 

Hopefully by the time go plugin 1.0 comes out, all this will be a moot point.

**Comment by dlsniper** [comment]
@gmack I don't understand why have you closed this. I've tried to understand the problem so that if indeed there's something that I can't replicate then it's added to the list of things to be fixed, hence the number of questions I've asked.

Moreover, IDEA 15 is **not** yet supported by the plugin and since you are now using a release that's a few months old chances are even more things will be broken for you (look at the changes from each version, you can see the notes here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases)

> Hopefully by the time go plugin 1.0 comes out, all this will be a moot point.

We need support from users who encounter problems like you in order for that to happen. So please, help us out to figure out what's wrong there and if it's something we need to better document or it's a problem with the plugin.

Thank you.
