### ISSUE TITLE
Upgrading to intellij 15 broke plugin installation

### ISSUE THREAD

**Issue by carmandrew** [go-lang-plugin-org/go-lang-idea-plugin#1958]
I upgraded to Intellij 15 today and am having trouble installing the plugin. I have the repository added like so:
<img width="425" alt="browse_repositories_and_preferences" src="https://cloud.githubusercontent.com/assets/630721/10921990/9456d030-822d-11e5-9f58-9756884a8520.png">

But when I click install I get this error:

<img width="399" alt="this_should_not_be_shown_and_browse_repositories_and_preferences" src="https://cloud.githubusercontent.com/assets/630721/10922002/ab519d10-822d-11e5-917e-11e067653e49.png">

For some reason, it seems to be trying to download from jetbrains.com instead of github release. Any ideas?

**Comment by dlsniper** [comment]
The plugin is now released into the official repository, see https://twitter.com/alex_zolotov/status/661605810661949440 so I suspect that's why, the version from alpha might be lower than the one from the official repo. That's only my guess, I don't really know how this might work. I'll investigate a bit on my own to see what's the status.

**Comment by dlsniper** [comment]
Ah, what happens if you try the nightly channel instead of alpha? Same issue?

**Comment by dlsniper** [comment]
I've checked the nightly channel just now and the plugin will update from 0.10.607 to 0.10.609 when adding the nightly channel. The alpha and stable channels have both 0.10.607 so I guess the IDE takes the official one as priority.

**Comment by carmandrew** [comment]
Aha! Yes, I just deleted the github source and it works now. Thanks for all
the hard work!
