### ISSUE TITLE
Auto fmt command after save action

### ISSUE THREAD

**Issue by hiromaily** [go-lang-plugin-org/go-lang-idea-plugin#2026]
Is it possible or having plan to develop?
It would be useful for me.

**Comment by dlsniper** [comment]
Hi, 

This topic has been covered a few times in the past. While I won't explain the reasons for this not being implemented, you can use search to find them, here are two ways you can do this:

- assign a shortcut to either gofmt or goimports actions and the use that instead of the save file one
- follow the instructions described here to configure the FileWatcher plugin to run gofmt on save http://stackoverflow.com/a/33776710/951414 hope it helps.
If you have any further questions, please let us know.

Kind regards, 
Florin

**Comment by hiromaily** [comment]
Thanks a lot!!
