### ISSUE TITLE
Import from parent/relative path is buggy

### ISSUE THREAD

**Issue by howesteve** [go-lang-plugin-org/go-lang-idea-plugin#2038]
Hello,

I'm using golang idea plugin version 0.10.734, go v1.5.1.

There seems to be a problem when importing a package from the parent folder:
```go
package main

import (
	p ".."
)

func main() {
}
```

While that is valid code, the "p ".."" line above will be highlighted as error, no symbol lookups on the imported "p" will be available, and all symbols prefixed by the package also will be highlited as error.

Thank you.

**Comment by dlsniper** [comment]
Hi, while this does look like a bug, I would strongly advise not to use relative imports, especially like that. 
On a different note, is the parent directory still part of the GOPATH that the plugin has configured? 
Thanks

**Comment by howesteve** [comment]
Yes, it is inside the GOPATH. What is the problem with a relative imports? It's just to organize internal packages more easily.

**Comment by dlsniper** [comment]
Thanks for the update, I guess it's a valid bug then.

As for your question, there are two threads on the mailing list which discuss this: https://groups.google.com/forum/#!msg/golang-nuts/n9d8RzVnadk/07f9RDlwLsYJ and https://groups.google.com/forum/#!topic/golang-nuts/zFVF7W-Y_y0

Especially with the plugin helping out in writing the import paths, it shouldn't too difficult to let the import path take it's full form, even if it feels a bit unnatural if you are coming from other languages. One of the reason is that if someone symlinks the dir that your main is and then decides to do a `go build` on it that will fail :)

Hope it helps and thanks once again for reporting.

**Comment by howesteve** [comment]
I'm not really going into the language discussion; I guess that is more for the golang-nuts list then idea-plugin? I think while the language still supports it (and it still does), it shouldn't highlight it as all sorts of errors.

Thanks!

**Comment by dlsniper** [comment]
Of course, I've just pointed it out because of the language itself. As for the bug, this is still open and once again, thank you for reporting.

**Comment by zolotov** [comment]
Works fine for me. Please share screenshot of your `Settings | Languages & Frameworks | Go | Go Libraries`
<img width="569" alt="screenshot 2015-11-25 20 09 06" src="https://cloud.githubusercontent.com/assets/140920/11403944/871a0420-93b0-11e5-92f3-744dadf396c1.png">
 configuration and tell me the path to the file you're editing.

**Comment by zolotov** [comment]
Works with alias as well
<img width="570" alt="screenshot 2015-11-25 20 10 49" src="https://cloud.githubusercontent.com/assets/140920/11403969/a9ddf02a-93b0-11e5-949d-e869ba1d3629.png">

> While that is valid code, the "p ".."" line above will be highlighted as error,

Btw, in the code you've attached it actually should be highlighted because it's unused. So could you check message of the inspection report?

**Comment by howesteve** [comment]
Ok got it problem was a trailing slash from my original code I forgot to post here:

```go
package main

import (
    p "../"
)

func main() {
}
```
Works on Go but raises the above issues  on the plugin. I've removed the slash from my code, it seems ok now but maybe if Go accepts it, the plugin should as well.

Thanks.

**Comment by dlsniper** [comment]
Sorry, I can't replicate it with Go.
Which go version are you using?
And can you please paste a screenshot of your code as well?

![snapshot144](https://cloud.githubusercontent.com/assets/607868/11405923/2f4cc19c-93ab-11e5-9990-97ce51ac72a5.png)

**Comment by dlsniper** [comment]
Updated the

**Comment by zolotov** [comment]
Thanks, will fix

**Comment by howesteve** [comment]
Here is a small demo video:

http://cudecurioso.com/idea-golang.mp4

**Comment by zolotov** [comment]
@howesteve thanks, we recreated the issue
