### ISSUE TITLE
Custom flags not applied to test invocations

### ISSUE THREAD

**Issue by mmindenhall** [go-lang-plugin-org/go-lang-idea-plugin#2054]
When I run a test or set of tests from the IDE, I want custom build flags I have currently set (via Settings -> Languages & Frameworks -> Go -> BuildFlags -> Custom flags) to be applied to the running tests.  

For example, if I have set `my_tag`, then when I run a test I want that flag to be set on the resulting test command that gets executed.  In the console I would then see a line like this:

```
/usr/local/Cellar/go/1.5.1/libexec/bin/go test -v -tags my_tag mypackage -run ^TestSomething$
```

**Comment by dlsniper** [comment]
Hi, thanks for reporting.
I understand why this is wanted but the Custom flags are there to help the resolving part do its job. For example I have distinct run configurations I work with regardless to what the flags for resolving are set to.

@zolotov what do you think, could there be any way to coordinate the settings from the Settings section with thr settings from the run configurations?

**Comment by zolotov** [comment]
Well, yes, I agree with @dlsniper resolving and running are different parts. For example, if I have an `integration` tag in order to separate unit and integration tests then for resolving I want to have `integration` tag but for running I want to set it only in one run configuration and do not set it in other one. If `-tags` will be set automatically that I wouldn't be able to create run configuration for unit tests only.

In order not to set `my_tag` tag every tim for each run configuration, you can modify its defaults:

<img width="1183" alt="screenshot 2015-12-01 12 37 19" src="https://cloud.githubusercontent.com/assets/140920/11497169/48a38d2a-9828-11e5-9ea6-d97c99bb0914.png">

**Comment by mmindenhall** [comment]
Closing this one, and filing a new one that I think is more clear.
