### ISSUE TITLE
Default tab width should be set to 8 (not 4)

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2082]
gofmt says:
"Gofmt formats Go programs. It uses tabs (width = 8) for indentation and blanks for alignment."
https://golang.org/cmd/gofmt/

I think we should default it to 8, people can then change it to something else if they prefer smaller tabs.

**Comment by iamzhout** [comment]
As to the latter part of @bits01 says, 
```I think we should default it to 8, people can then change it to something else if they prefer smaller tabs```

now the default tab identation is 8, and there is no way to change it to other values, right?

**Comment by dlsniper** [comment]
@iamzhout only the default indentation size has been changed. Should you wish to use a different size, 2 or 4 for example, simply go to File -> Settings -> Editor -> Code Style -> Go and there change the indentation values accordingly.

**Comment by iamzhout** [comment]
@dlsniper It works great. 
and seems the problem is about the filter(see below picture), 
as I am not sure where is the configuration item that takes effect, I try to filter by keyword, and Go "Code Style" setting is missing in filter result, maybe this could be fixed.

![20160104_tabsize_filter](https://cloud.githubusercontent.com/assets/14846203/12085782/a303bcf4-b2fe-11e5-909c-436d67bea25d.PNG)

**Comment by dlsniper** [comment]
@iamzhout I've never noticed. Thanks. I've opened up a new issue for this.

**Comment by iamzhout** [comment]
@dlsniper OK, thanks :)
