### ISSUE TITLE
not finding $GOPATH package imports

### ISSUE THREAD

**Issue by FAQinghere** [go-lang-plugin-org/go-lang-idea-plugin#224]
I cannot get the plugin to find the packages imported into my projects.

Right now I'm trying the simplest possible structure - exactly per the Go docs:

mine
$HOME/go/src/mycompany/myproject/hello.go
imported
$HOME/go/src/thirdparty/theirproject/say.go

import "theirproject/say"

go get

Everything works fine (predictably) from the command line. But still the plugin is not able to find the imported package.

I tried fiddling with the project structure (adding the gopath src directory as a library, etc), but to no avail.

Could anybody shed some light on how to get the plugin to pick up the installed packages (obviously located in $GOPATH/src)?

**Comment by JackleZhang** [comment]
I have resolved this problem via mac's ln demand. 
This problem is just how can your idea find the root package path. 
For example, My $GOPATH is ~/mygo . I just create symbolic link like this. 
` ln -s $GOROOT/src ~/mygo `
Mean while, In my idea, File -> Project Settings -> Libraries   add GOPATH<root> import my  symbolic link like ~/mygo  and restart idea.
