### ISSUE TITLE
Code completion with `if err != nil {...}`

### ISSUE THREAD

**Issue by mynameismevin** [go-lang-plugin-org/go-lang-idea-plugin#2315]
- **What version of Go plugin are you using?**

0.10.749

- **What version of IDEA are you using?**

PyCharms 5.0.3

- **What version of Java are you using?**

JDK that comes with PyCharms for OS X.

- **What did you do?**

Typed `if` and tab completed the `if err != nil` fill-in.

- **What did you expect to see?
**
Have the plugin fill in:
```go
if err != nil {
    
}
```

- **What did you see instead?**

Two `if`s with the completion.
```go
if if err != nil {

}
```

**Comment by zolotov** [comment]
@mynameismevin Hi. It happens because `Tab` is key for expanding live template and `err` is a live template for 

```go
if err != nil {
}
```

Indeed, it shouldn't be available just after `if` keyword and I'll fix it. Meanwhile you can use following possible workarounds:

- use `err` live template without manually typing `if` keyword before
- disable `err` live template in File | Settings | Editor | Live Templates
- change live template expanding key for all templates or only for `err` template in File | Settings | Editor | Live Templates

**Comment by mynameismevin** [comment]
Awesome, thanks for the workarounds!
