### ISSUE TITLE
After 0.10.607 no Go App Engine run configuration

### ISSUE THREAD

**Issue by tobwiens** [go-lang-plugin-org/go-lang-idea-plugin#2355]
I updated from 0.10.607 to 0.10.1137 and my "Go App Engine" run configuration broke. The setting is not available anymore.

**Comment by zolotov** [comment]
Hi @tobwiens. Sorry for late response. Please share your logs with https://gist.githib.com (Help | Show Logs in <file browser>)

**Comment by ChristianSiegert** [comment]
@zolotov I’m not OP but have the same problem.

There are many log files and I don’t know which one is relevant because some time has passed since I updated to the go-lang-plugin version where the bug is present. For a better understanding of what we mean I attached a screenshot.

![2016-03-02 go-lang-idea-plugin bug](https://cloud.githubusercontent.com/assets/179736/13462818/9314e562-e089-11e5-9465-c51f2d1020ea.png)

I use go-lang-idea-plugin version 0.10.1137 in JetBrains WebStorm 11.0.3.

**Comment by zolotov** [comment]
> There are many log files

I believe `idea.log` is enough

**Comment by zolotov** [comment]
Should be fixed now, please update plugin

**Comment by ChristianSiegert** [comment]
Thanks, it works in the latest version.
