### ISSUE TITLE
gb support

### ISSUE THREAD

**Issue by anidotnet** [go-lang-plugin-org/go-lang-idea-plugin#2357]
- Plugin version (or commit hash): 0.10.1137
- IDE name and version: IntelliJ IDEA 15.0.3

Support for the golang build tool - [gb](https://getgb.io/) would be great. I know it is not an official tool but IMO it is better than the built-in one (and hey delve is supported in the plugin!). It also has the vendor management feature and most importantly does not honour GOPATH, so that we can have a project structure of our own. It would be better to have that support in the IDE.

**Comment by dlsniper** [comment]
> and hey delve is supported in the plugin! 

Delve is a special case as it's the only debugger with proper support for  Go (or was until LLDB got some support, haven't tried it yet). It's also cross-platform, don't know about others. So this is a special case, and I hope you can agree to it.

> and most importantly does not honour GOPATH

Subjective and very bad as it goes against the system defined in the language manual. The plugin tries to follow the manual :)

> It would be better to have that support in the IDE.

Sure, and as mentioned here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1636#issuecomment-104239983 (the comments afterwards) we happy accept contributions for `gb`. Otherwise this is a very(?) low priority afaik.

I'll leave this for others to find it easier.
