### ISSUE TITLE
Refactoring Module Name should rename package in source files

### ISSUE THREAD

**Issue by bd12** [go-lang-plugin-org/go-lang-idea-plugin#2358]
- Plugin version (or commit hash): 0.10.1137
- IDE name and version: Intellij 15.0.3
- Java version: OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
  OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
- OS name and version: Ubuntu 15.10
- What are you trying to do? Refactor the name of a module(folder) by refactor -> rename functionality
- What would you expect to happen? Given that there is no syntax error, all other files referencing the renamed module obtain updated references
- What happens? refactoring doesn't rename the package of the source files.

steps for reproduction:
1. create main.go within package "main"
2. create second src file "file2.go" within a different module "bug"
3. refactor the module name

-> the package reference within file2.go is not updated

**Comment by zolotov** [comment]
> -> the package reference within file2.go is not updated

Which reference? I don't see any references in step for reproduction. Directory name and package name are independent entities.

**Comment by horkhe** [comment]
Lets say we have a package `foo` with path `examples.com/foo` that consistst of just one file `examples.com/foo/foo.go` that looks as follows:

```go
package foo

def F() {
}
```

Package `foo` is imported in `bar.go`, that looks like this:

```Go
package bar

import "examples.com/foo"

def F() {
    foo.F()
}
```

In this example package `foo` source files are located in a directory of the same name according to the Go coding convention (the name of the directory could have been different, compiler would allow that). However in references to functions, types and variables from other packages the `foo.` part comes from the package name rather than from the directory name. So:

**What are you trying to do?**: rename directory `foo` that contains package `foo` to `blah`:

**Expected behavior**: file `bar.go` looks as follows:

```Go
package bar

import "examples.com/blah"  // foo changed to blah

def F() {
    foo.F()  // still foo, because the package name is not changed
}
```

**Actual behavior**:

```Go
package bar

import "examples.com/blah"  // foo changed to blah, corretly

def F() {
    blah.F()  // change to foo, rendering code syntactically incorrect because the package name has not been changed.
}
```

Since according to the Go cording convention packages source files should be located in a directory of the same name it makes sence whenever a package name or a directory name is renamed suggest to also rename the other with a checkbox enabled by default.

Hope that helps.
