### ISSUE TITLE
legal expression is flagged as syntax error 

### ISSUE THREAD

**Issue by howesteve** [go-lang-plugin-org/go-lang-idea-plugin#2431]
- Plugin version (or commit hash): 0.11.1253

- Java/IDE version:
WebStorm 2016.1.1
Build #WS-145.597, built on March 30, 2016
JRE: 1.8.0_77-b03 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation

- OS name and version: Arch Linux / hp 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

- What happens?
Golang plugin highlights legal expression as an error, while it's compiled normally (using Go 1.6).
![screenshot_2016-04-01_23-55-15](https://cloud.githubusercontent.com/assets/3008471/14224114/05670c72-f867-11e5-9c77-81a0db886fce.png)

```go
package main

type Handler func()

func main() {
	x := Handler(func(){})
	handlers := []*Handler{&x}
	for _, handler := range handlers {
		(*handler)()
	}
}
```

**Comment by sjamesr** [comment]
The problem seems to be that the plugin's Go parser tries to treat call expressions and conversion expressions independently, whereas they are actually indistinguishable at parse time.

e.g. `(f)(x)` is either a type conversion if `f` is a type reference expression or a function call if not.

I believe the go parser treats conversions and calls the same way.

```
|       convtype '(' expr ocomma ')'
        {
                // conversion (e.g. (chan *bytes.Buffer)(b))
                $$ = Nod(OCALL, $1, nil);
                $$.List = list1($3);
        }
```

Note that the node inserted is of type `OCALL`, which is the same used in call expressions:

```
|       pexpr '(' expr_or_type_list ocomma ')'
        {
                $$ = Nod(OCALL, $1, nil);
                $$.List = $3;
        }
```

Not sure what the solution is, but I think the current way the grammar is defined can't work.

**Comment by ignatov** [comment]
Duplicates #2410
