### ISSUE TITLE
Auto import is importing the wrong package

### ISSUE THREAD

**Issue by aanm** [go-lang-plugin-org/go-lang-idea-plugin#2463]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: IntelliJ IDEA 2016.1.1 Build #IC-145.597, built on March 29, 2016
- Java version: JRE: 1.8.0_76-release-b18 amd64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: Fedora 23 x86_64

- What are you trying to do?
Writing a normal golang using the package `fmt` without being imported.

- What would you expect to happen?
To auto import the correct `fmt` package or not importing at all

- What happens?
When I'm writing code, see example, the plugin automatically imports the `fmt` package. This is fine but the package that imports is `"github.com/golang/go/src/fmt"` where it should only be `"fmt"`.

Example code.
```go
package main

import (
)

func main() {
	fmt.Println("Hello, playground!")
}
```

Wait one second or so and the `"github.com/golang/go/src/fmt"` shows up.

```go
package main

import (
        "github.com/golang/go/src/fmt"
)

func main() {
	fmt.Println("Hello, playground!")
}
```

Is it possible to disable the auto import feature if this can't be fixed?

**Comment by dlsniper** [comment]
@aanm That's partially not true. The package is correct, and it even provides the correct function. The problem is that you are not supposed to have the Go source in the GOPATH. If you are developing on Go you should have it under `~/go` (and the Go 1.4 should be in `~/go1.4`). The plugin is correct to resolve that.
Even if we solve: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2446 that location would still be a valid package location (by definition) and provide a proper resolution for the function at hand.

@zolotov the reason I say partially true is that, the location, according to a test I've just done against Go 1.6 is like this:
```
demo.go:4:2: cannot find package "log1" in any of:
        /home/florin/golang/src/github.com/dlsniper/demo/vendor/log1 (vendor tree)
        /usr/local/go/src/log1 (from $GOROOT)
        /home/florin/golang/src/log1 (from $GOPATH)
```

So it's: vendor then GOROOT then GOPATH.
As such, I leave this with you to decide if we should close this or keep it open for the order of priority for Go packages (I'll ask around if this means you can override internal packages with vendored ones which seems like a fun one)

**Comment by aanm** [comment]
@dlsniper Thanks for the clarification.

I would vote for something like system > vendor > gopath

**Comment by dlsniper** [comment]
I'm not familiar with this subsystem but I would still like to have it as Go itself does

**Comment by zolotov** [comment]
@aanm I cannot recreate the issue. How did you configure Go Libraries and SDK in IDE?

> As such, I leave this with you to decide if we should close this or keep it open for the order of priority for Go packages (I'll ask around if this means you can override internal packages with vendored ones which seems like a fun one)

IDE won't suggest import that are shadowed by vendor directory or GOROOT.

> I would vote for something like system > vendor > gopath

It's not about voting, it's how `go` compiler works, and @dlsniper is right, it's vendor->goroot->gopath

**Comment by aanm** [comment]
@zolotov Thanks for trying that out. With a new project I couldn't replicate it. It always tell me that fmt has multiple choices and doesn't automatically go to GOPATH. So I took a look at it and for some reason I had Project SDK 1.5 instead of Go 1.6 in the Module SDK.

Thanks to @dlsniper too
