### ISSUE TITLE
Intellij IDEA IU-141.1532.4 java1.8.0_77 build error

### ISSUE THREAD

**Issue by phoenixchang** [go-lang-plugin-org/go-lang-idea-plugin#2776]
go-lang-idea-plugin-master/plan9/gen/com/plan9/intel/lang/core/parser/AsmIntelParser.javaError:(84, 16) java: 对于enter_section_(com.intellij.lang.PsiBuilder,int,int,com.intellij.psi.tree.IElementType,java.lang.String), 找不到合适的方法
    方法 com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(com.intellij.lang.PsiBuilder,int,int,java.lang.String)不适用  (实际参数列表和形式参数列表长度不同)
    方法 com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(com.intellij.lang.PsiBuilder)不适用(实际参数列表和形式参数列表长度不同)

the function defination is:
public static Marker enter_section_(PsiBuilder var0, int var1, int var2, @Nullable String var3) {
        Marker var4 = var0.mark();
        a(var0, var1, var2, var3);
        return var4;
}

**Comment by dlsniper** [comment]
It is not possible to build the latest master against idea 14.1. Please use the latest IDEA version (2016.2) or the previous version, 2016.1.
Otherwise you have to figure out how to make it compile, sorry. 
If you are trying to get the latest version of the plugin, just see the readme and use the nightly channel in one of the supported releases.
