### ISSUE TITLE
gofmt

### ISSUE THREAD

**Issue by biamorton** [go-lang-plugin-org/go-lang-idea-plugin#2783]
Any chance we could get gofmt on this plugin?

**Comment by dlsniper** [comment]
gofmt as well goimports have been present in the plugin for a very long time.
Please have a look at ` Code | Go Tools ` menu. You can even bind a shortcut for these actions or invoke them from the right click command.

**Comment by dlsniper** [comment]
Please let me know If you have any issues in using these, I'll close this for now. Thank you.

**Comment by biamorton** [comment]
Wow, thanks. Totally missed that. Unfortunately its grayed out for me. tried focusing on the code first and on the file in the explorer and still nothing :( Maybe some settings i dont have? Also any way to make it run on file save?

**Comment by dlsniper** [comment]
Hi @biamorton.

If it's grayed out it can be because:
- either the current file is not a Go file or it's not selected (the editor doesn't have the focus)
- the tool is not found (in case it's goimports)

If you still have troubles running it after checking those two, please let me know.
As for running it automatically, I think this post covers it pretty well: http://www.idmworks.com/automatically-calling-go-fmt-from-intellij-2/ Hope it helps.

If you have any further issues, please write back. Thank you.
