### ISSUE TITLE
Hello World Project Setup

### ISSUE THREAD

**Issue by gmseed** [go-lang-plugin-org/go-lang-idea-plugin#2830]
Just installed version 2016.2.5 of the Community edition of IntelliJ and then installed the Go plugin from:

https://plugins.jetbrains.com/plugin/5047

I followed the wizard for creating a new project but when I come to run a simple hello.go file I get a "Main file is invalid" in the "Run Configurations" dialog.

Does anyone know of a step by step guide to setting up and running the simplest of Go projects?

It has to be said that the online documentation is absolutely crap. Alo, on the "Run Configurations" dialog if I click "Help" I get a 404 invalid page.

Thanks Graham

**Comment by zolotov** [comment]
Please see `https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#running-your-application`. 

The easiest way to run simple application is to create go file with `hello world`-like context, right click on it and choose `Run`. 

More descriptive guides can be found via Google, e.g. http://hadihariri.com/2015/09/30/setting-up-go-on-intellij/, https://rootpd.com/2016/02/04/setting-up-intellij-idea-for-your-first-golang-project/, http://networkstatic.net/installing-golang-ide-support-intellij/, etc.

As for `Main file is invalid`, it means just what it says – something wrong with the file that you set in Run Configuration: it cannot be found or it's not a Go file.

**Comment by mikeschinkel** [comment]
I was having the same problem and could not figure out what was wrong with my `main.go` file. 

Turns out _nothing_ was wrong with my `main.go` file, what was wrong was my build configuration!  When you click [+] and then "Go Build" in the Run/Debug Configurations it defaults to a **directory** in the "File" field, and my eyes just glossed over that and I could not "see" it.  

I finally figured it out after I right-clicked on `main.go` and then selected "Run 'go build main.go'."  Doh!  

Hope this helps someone else not struggle with this for as long as I did.

**Comment by twisstosin** [comment]
Solved this by changing the main go file's package name to "main", then hitting the [+] build configurations then set the "File" field to the main file directory e.g `C:/Users/twisstosin/go/src/github.com/twisstosin/[PROJECT-NAME]/Main.go`, then apply and should be good to `go.`
