### ISSUE TITLE
Built-in symbols flagged as "unresolved"

### ISSUE THREAD

**Issue by mindplay-dk** [go-lang-plugin-org/go-lang-idea-plugin#362]
I'm using the latest build (published 8 hrs ago) with PhpStorm 7.1 (133.214) and the built-in symbols like `make()` and `len()` are flagged with an "unresolved symbol" inspection.

Do I need to configure or do anything special to make this work?

**Comment by francoishill** [comment]
@n Your solution fixed it. Setting the SDK in Project Structure. Thanks!

**Comment by dlsniper** [comment]
@francoishill what are you talking about? What problem did you had and you fixed? Which plugin version are you using? What IDE?

**Comment by francoishill** [comment]
@dlsniper  Not sure what version but this issue we are in now is about the IDEA golang plugin. Note the url of this issue - https://github.com/go-lang-plugin-org/go-lang-idea-plugin. My problem was that the golang builtin types (like `int64`, `string`, etc) showed "undefined type". But it was because my Go SDK path was incorrectly setup. Like mr "n" explained above with screenshots and all: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/362#issuecomment-38237194

**Comment by dlsniper** [comment]
> Not sure what version but this issue we are in now is about the IDEA golang plugin.

Ok, I'm not sure if I can actually help with anything the description applies to a very old version of the plugin. Please use the latest release for IDEA and the plugin is available for it already.

**Comment by francoishill** [comment]
Thanks for being so helpful @dlsniper but I actually came right and do not need help. That is actually the message I tried carry over with my initial comment on this issue. It was indeed nothing wrong with the plugin itself.

Why it broke was because I manually moved my directories containing my go workspace and go binaries (GOROOT). So I updated all the relevant environment variables. But IDEA suddenly gave me this "undefined" issue. So I just had to update my SDK path to where I moved my stuff and that resolved the issue immediately.

But thanks again for your helpfulness.

**Comment by markfink** [comment]
I want to bring home my Go coding to IDEA IDE but I can not manage to resolve builtin types (e.g. all my strings, int64, etc. are marked as errors, for me this basically makes IDEA unusable for go coding)
Idea 14.1.5
Go lang plugin 0.9.748
Ubuntu 15.10

I could not resolve any types but I managed to tune the settings (see below) and now the problem is reduced to builtin types. The problem I have with all my IDEA go projects. 

in Settings >Language&Frameworks>Go>Go Libraries   I have the following settings 
project libraries:
/usr/lib/go/src
project libraries:
/home/mark/devel/gocode
(I am not using GOLANG env variable since I am starting from the /opt/idea/idea.sh)

Above discussion mentions that this issue only happen if one starts a project from source??? So is there a workaround to start a new project from scratch and is this still valid?

**Comment by zolotov** [comment]
@markfink all discussion above is outdated since we've reimplement whole plugin. Please check that you've set Go SDK for project and for module (`File | Project Structure | Project` and `File | Project Structure | Modules | <your module>`)

**Comment by markfink** [comment]
two things:
i) the issue seems to be still relevant. I followed your documentation (https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation) to setup your plugin.
ii) your workaround with the module setup does not work for me. I put /usr/lib/go/src and /usr/lib/go into all library buckets and still does not recognize the golang builtins. What are modules anyway. I do not thing golang has them.
Do you think I could use the old version of the plugin where builtins work? which version would be good? Any advice on how to debug / get more info on what is wrong?

**Comment by zolotov** [comment]
@markfink this version is quite stable and works well for many users so I'm sure it's just misconfiguration. Please remove all paths from Go Libraries and attach screenshots of configuration dialogs `File | Project Structure | Project` and `File | Project Structure | Modules | <your module>`

**Comment by markfink** [comment]
![image](https://cloud.githubusercontent.com/assets/33456/12018197/529e7f22-ad60-11e5-9a6b-e7b4593f6e4a.png)
I removed the paths and to be save "Invalidated cache" - still no luck.

**Comment by zolotov** [comment]
1. I still see the paths in project and module sections
2. I asked to screenshots of `File | Project Structure | Project` and `File | Project Structure | Modules | <your module>`
3. Also please attach screenshot of whole IDE window with opened Go file

**Comment by francoishill** [comment]
Yes @markfink please check the settings in your [Project Structure -> SDKs]. The `Go SDK home path` should be correct too. I agree the setting is in a non-obvious place because I also had this issue a while ago.

**Comment by markfink** [comment]
yeah I see. correct is such a relative term ...unless it works.
![image](https://cloud.githubusercontent.com/assets/33456/12018556/b54bf6f0-ad64-11e5-976b-2bf4a011c283.png)
![image](https://cloud.githubusercontent.com/assets/33456/12018559/c16595f4-ad64-11e5-9e7e-96fa55d37cda.png)
![image](https://cloud.githubusercontent.com/assets/33456/12018561/d254f0bc-ad64-11e5-9f1f-d44d052d1a0d.png)

**Comment by zolotov** [comment]
@markfink and what's in Dependencies tab?

And one more time:

> Also please attach screenshot of whole IDE window with opened Go file

**Comment by markfink** [comment]
![image](https://cloud.githubusercontent.com/assets/33456/12018663/2a9a72dc-ad66-11e5-9e0e-09e574ad0177.png)


![image](https://cloud.githubusercontent.com/assets/33456/12018649/e4976790-ad65-11e5-9239-39dce5f364bc.png)

**Comment by zolotov** [comment]
> the builtin is there....

builtin shouldn't be there. please remove GOROOT path from Go Libraries configurable

**Comment by markfink** [comment]
I recreated the Go SDK and now the problem is gone. The Go installation was updated caused by OS updates from 1.3.3 -> 1.5.1. Obviously the project configuration could not deal with that. Recreating the SDK solved the issue for me. Thanks for pointing me in the right direction!

**Comment by zolotov** [comment]
@markfink thanks for update. It's hard to suggest such case, I'm glad you've solved the issue.
